#!/bin/sh

# re-build the project to latest versions of config files

flutter create . \
	--empty \
	--org com.darwinsys \
	--overwrite \
	--platforms android,ios,web \
	--project-name flutter_template \
